### PR TITLE
small fix - fixed type checking for filter operation

### PR DESCRIPTION
**Pull request by AlexanderBich**
Thanks for the lib, I will post fixes here, so please make sure to check your notifications)

### CODE REVIEW

**Comment by rayman1104** [comment]
Cool, thanks. Is it ready to merge?

**Comment by Brunni** [comment]
Thank you for the fix. I really need it for boolean filters! Can it be published?

**Comment by rayman1104** [comment]
@Brunni must be published, isn't it? Version 1.1.7.

**Comment by Brunni** [comment]
@rayman1104 In 1.1.7 version it is still the old check in the index.js file:

```
if (typeof flatFilter[key] === 'number' || flatFilter[key].match(/^\d+$/)) {
                ops = crud_request_1.CondOperator.EQUALS;
}
```

**Pull request merged**
